// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLGNCWNDv2guAgEENeX4xm4PZcAe5JOO4',
    appId: '1:766964719432:web:3ce25180662465ba7add7d',
    messagingSenderId: '766964719432',
    projectId: 'mlock-f',
    authDomain: 'mlock-f.firebaseapp.com',
    storageBucket: 'mlock-f.firebasestorage.app',
    measurementId: 'G-VX1JXKMWC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDajaW_bAJDdliSssLpq17awwm6muGLJgM',
    appId: '1:766964719432:android:702d9544d7ced0d67add7d',
    messagingSenderId: '766964719432',
    projectId: 'mlock-f',
    storageBucket: 'mlock-f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJblH-G9wqKdQihOapsNcM0KFUBPIr0u4',
    appId: '1:766964719432:ios:b245ad3c91c7b39f7add7d',
    messagingSenderId: '766964719432',
    projectId: 'mlock-f',
    storageBucket: 'mlock-f.firebasestorage.app',
    iosBundleId: 'com.example.mlockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJblH-G9wqKdQihOapsNcM0KFUBPIr0u4',
    appId: '1:766964719432:ios:b245ad3c91c7b39f7add7d',
    messagingSenderId: '766964719432',
    projectId: 'mlock-f',
    storageBucket: 'mlock-f.firebasestorage.app',
    iosBundleId: 'com.example.mlockFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLGNCWNDv2guAgEENeX4xm4PZcAe5JOO4',
    appId: '1:766964719432:web:d02631bc0ef66acf7add7d',
    messagingSenderId: '766964719432',
    projectId: 'mlock-f',
    authDomain: 'mlock-f.firebaseapp.com',
    storageBucket: 'mlock-f.firebasestorage.app',
    measurementId: 'G-V38BE6VH0J',
  );
}
